version: '3'

services:
  
  worker1:
    build:
      context: .
      dockerfile: Dip aockerfile
    command: java -jar app.jar
    environment:
      - QUEUE_NAME=autoDeleteQueueAlcanzable
    ports:
      - "8080:8080"  # Puertos de la aplicación en el contenedor
    depends_on:
      - rabbitmq

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar app.jar
    environment:
      - QUEUE_NAME=autoDeleteQueueQr
    ports:
      - "8081:8080"  # Puertos de la aplicación en el contenedor
    depends_on:
      - rabbitmq
      
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Monta el script SQL en el directorio de inicialización
    command: --init-file=/docker-entrypoint-initdb.d/init.sql  # Ejecuta el script SQL durante la inicialización

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - mysql

volumes:
  mysql_data:  # Creará automáticamente el volumen mysql_data tengo eso pero quiero que al levantarse cree una tabla llamada urlServices sino existe
