version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Monta el script SQL en el directorio de inicializaci칩n
    command: --init-file=/docker-entrypoint-initdb.d/init.sql  # Ejecuta el script SQL durante la inicializaci칩n

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - mysql

volumes:
  mysql_data:  # Crear치 autom치ticamente el volumen mysql_data tengo eso pero quiero que al levantarse cree una tabla llamada urlServices sino existe
